version: 2
aliases:
  - &container_python
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job

  - &run_task_install_tox_dependencies
    run:
      name: install tox dependencies
      command: |
        sudo apt-get -qq update
        sudo apt install -y build-essential libssl-dev libpython-dev python python-pip
        sudo pip install tox

jobs:
  testing:
    <<: *container_python
    steps:
      - checkout
      - *run_task_install_tox_dependencies
      - run:
          name: execute the pytests documentation
          command: |
            tox -e test
      - store_test_results:
          path: .tox/test/tmp/reports
  builddocs:
    <<: *container_python
    steps:
      - checkout
      - *run_task_install_tox_dependencies
      - run:
          name: build the sphinx documentation
          command: |
            tox -e docs

workflows:
  version: 2
  build_and_test:
    jobs:
      - testing
      - builddocs
